managementApiSecret: PRISMA_MANAGEMENT_API_SECRET
port: 4466
databases:
  default:
    connector: mysql
    host: SQL_HOST
    port: 3306
    user: root
    password: SQL_PASSWORD
    migrations: true
    active: true
  production:
    connector: mysql
    host: SQL_HOST
    port: 3306
    user: root
    password: SQL_PASSWORD
    migrations: true
    active: true
